
package homework.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PersonAlreadyExists", targetNamespace = "http://template/")
public class PersonAlreadyExists_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonAlreadyExists faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PersonAlreadyExists_Exception(String message, PersonAlreadyExists faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PersonAlreadyExists_Exception(String message, PersonAlreadyExists faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: homework.wsdl.PersonAlreadyExists
     */
    public PersonAlreadyExists getFaultInfo() {
        return faultInfo;
    }

}
