
package homework.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PersonNotFound", targetNamespace = "http://template/")
public class PersonNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PersonNotFound_Exception(String message, PersonNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PersonNotFound_Exception(String message, PersonNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: homework.wsdl.PersonNotFound
     */
    public PersonNotFound getFaultInfo() {
        return faultInfo;
    }

}
