
package homework.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PersonServiceWrapped", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/PersonSoapBare/service?wsdl")
public class PersonServiceWrapped
    extends Service
{

    private final static URL PERSONSERVICEWRAPPED_WSDL_LOCATION;
    private final static WebServiceException PERSONSERVICEWRAPPED_EXCEPTION;
    private final static QName PERSONSERVICEWRAPPED_QNAME = new QName("http://service/", "PersonServiceWrapped");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PersonSoapBare/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSERVICEWRAPPED_WSDL_LOCATION = url;
        PERSONSERVICEWRAPPED_EXCEPTION = e;
    }

    public PersonServiceWrapped() {
        super(__getWsdlLocation(), PERSONSERVICEWRAPPED_QNAME);
    }

    public PersonServiceWrapped(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSERVICEWRAPPED_QNAME, features);
    }

    public PersonServiceWrapped(URL wsdlLocation) {
        super(wsdlLocation, PERSONSERVICEWRAPPED_QNAME);
    }

    public PersonServiceWrapped(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSERVICEWRAPPED_QNAME, features);
    }

    public PersonServiceWrapped(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServiceWrapped(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonServiceTemplate
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonServiceTemplate getPersonServicePort() {
        return super.getPort(new QName("http://service/", "PersonServicePort"), PersonServiceTemplate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonServiceTemplate
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonServiceTemplate getPersonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "PersonServicePort"), PersonServiceTemplate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSERVICEWRAPPED_EXCEPTION!= null) {
            throw PERSONSERVICEWRAPPED_EXCEPTION;
        }
        return PERSONSERVICEWRAPPED_WSDL_LOCATION;
    }

}
