
package wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "AmountNotPositive", targetNamespace = "http://template/")
public class AmountNotPositive_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AmountNotPositive faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AmountNotPositive_Exception(String message, AmountNotPositive faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AmountNotPositive_Exception(String message, AmountNotPositive faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsdl.AmountNotPositive
     */
    public AmountNotPositive getFaultInfo() {
        return faultInfo;
    }

}
