
package wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "DuplicateFault", targetNamespace = "http://template/")
public class DuplicateFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DuplicateFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DuplicateFault_Exception(String message, DuplicateFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DuplicateFault_Exception(String message, DuplicateFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsdl.DuplicateFault
     */
    public DuplicateFault getFaultInfo() {
        return faultInfo;
    }

}
