
package wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "InternalError", targetNamespace = "http://template/")
public class InternalError_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InternalError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InternalError_Exception(String message, InternalError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InternalError_Exception(String message, InternalError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsdl.InternalError
     */
    public InternalError getFaultInfo() {
        return faultInfo;
    }

}
