
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServiceA", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/ServiceA/service?wsdl")
public class ServiceA
    extends Service
{

    private final static URL SERVICEA_WSDL_LOCATION;
    private final static WebServiceException SERVICEA_EXCEPTION;
    private final static QName SERVICEA_QNAME = new QName("http://service/", "ServiceA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServiceA/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEA_WSDL_LOCATION = url;
        SERVICEA_EXCEPTION = e;
    }

    public ServiceA() {
        super(__getWsdlLocation(), SERVICEA_QNAME);
    }

    public ServiceA(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEA_QNAME, features);
    }

    public ServiceA(URL wsdlLocation) {
        super(wsdlLocation, SERVICEA_QNAME);
    }

    public ServiceA(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEA_QNAME, features);
    }

    public ServiceA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceA(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceTemplate
     */
    @WebEndpoint(name = "ServicePort")
    public ServiceTemplate getServicePort() {
        return super.getPort(new QName("http://service/", "ServicePort"), ServiceTemplate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceTemplate
     */
    @WebEndpoint(name = "ServicePort")
    public ServiceTemplate getServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "ServicePort"), ServiceTemplate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEA_EXCEPTION!= null) {
            throw SERVICEA_EXCEPTION;
        }
        return SERVICEA_WSDL_LOCATION;
    }

}
