
package wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TransactionNotFound", targetNamespace = "http://template/")
public class TransactionNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TransactionNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TransactionNotFound_Exception(String message, TransactionNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TransactionNotFound_Exception(String message, TransactionNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsdl.TransactionNotFound
     */
    public TransactionNotFound getFaultInfo() {
        return faultInfo;
    }

}
